services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
    container_name: nimbusagent
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-""}